# Generated by Django 4.2.15 on 2024-09-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='test@gmail.com', help_text='Enter your email', max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
