# Generated by Django 4.2.15 on 2024-08-28 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "bus_number",
                    models.CharField(
                        help_text="Unique identifier for the bus (e.g., ABC123).",
                        max_length=20,
                        unique=True,
                        verbose_name="Bus Number",
                    ),
                ),
                (
                    "bus_type",
                    models.CharField(
                        choices=[("ac", "Air Conditioned"), ("non_ac", "Non Air Conditioned")],
                        default="non_ac",
                        help_text="Type of the bus (e.g., Air Conditioned, Sleeper).",
                        max_length=20,
                        verbose_name="Bus Type",
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(help_text="Total number of seats available on the bus.", verbose_name="Capacity"),
                ),
                (
                    "availability_status",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the bus is available for booking.",
                        verbose_name="Availability Status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_location",
                    models.CharField(
                        help_text="Starting point of the bus route.", max_length=100, verbose_name="Start Location"
                    ),
                ),
                (
                    "end_location",
                    models.CharField(
                        help_text="Ending point of the bus route.", max_length=100, verbose_name="End Location"
                    ),
                ),
                ("stops", models.TextField(help_text="Comma separated list of intermediate stops.", verbose_name="Stops")),
                (
                    "scheduled_time",
                    models.TimeField(help_text="Scheduled departure time of the bus.", verbose_name="Scheduled Time"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "date",
                    models.DateField(help_text="Date on which the bus is scheduled for this route.", verbose_name="Date"),
                ),
                (
                    "available_seats",
                    models.IntegerField(
                        help_text="Number of seats available for booking on this bus.", verbose_name="Available Seats"
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        help_text="Select the bus for this route.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus.bus",
                        verbose_name="Bus",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        help_text="Select the route for this bus.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus.route",
                        verbose_name="Route",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "seat_numbers",
                    models.IntegerField(
                        help_text="The list of seat numbers assigned to the user for this route.",
                        verbose_name="Seat Numbers",
                    ),
                ),
                (
                    "bus_route",
                    models.ForeignKey(
                        help_text="The specific bus and route being booked.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus.busroute",
                        verbose_name="Bus Route",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "booking_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Time when the booking was made.", verbose_name="Booking Time"
                    ),
                ),
                (
                    "book",
                    models.ManyToManyField(
                        help_text="Multiple booking for different route", to="bus.bookingdetail", verbose_name="Book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user making the booking.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
