name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgis/postgis:13-3.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and run containers
      run: |
        docker-compose up -d --build
        
    - name: Check for pending migrations
      env:
        DJANGO_SECRET_KEY: test
        DB_HOST: localhost
        DB_NAME: postgres
        DB_USER: postgres
        DB_PASSWORD: postgres
      run: |
        docker-compose run --env-file .env web python manage.py makemigrations --check --dry-run
        
    - name: Run tests with pytest
      env:
        DJANGO_SECRET_KEY: test
        DB_HOST: localhost  
        DB_NAME: postgres
        DB_USER: postgres
        DB_PASSWORD: postgres
      run: |
        docker-compose run --env-file .env web pytest

    - name: Cleanup
      run: |
        docker-compose down
